### ISSUE TITLE
mobile-ui: task does not show the assignee

### ISSUE THREAD

**Issue by abstratt** [abstratt/kirra#35]
Also, it allows the user to attempt to change it, but it does not make the required change.

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:139)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:70)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
	... 96 more

**Comment by abstratt** [comment]
![image](https://cloud.githubusercontent.com/assets/2187522/22866275/b96067c2-f15a-11e6-9ba3-9184e9d0de58.png)

**Comment by abstratt** [comment]
![image](https://cloud.githubusercontent.com/assets/2187522/22866294/07c75830-f15b-11e6-9040-c355eb39df7f.png)

**Comment by abstratt** [comment]
The qooxdoo UI is no longer being maintained.
